name: 'Register build artifacts in Platform'
description: 'Report artifact data and version produced by a GHA workflow run to the CloudBees platform.'

branding:
  icon: 'command'
  color: 'purple'

inputs:
  cloudbees-url:
    description: 'The CloudBees platform URL.'
    required: false
    default: "https://api.cloudbees.io"
  cloudbees-pat:
    description: 'The CloudBees platform personal access token.'
    required: true
  name:
    description: 'The name of the artifact.'
    required: true
  version:
    description: 'The version of the artifact.'
    required: true
  url:
    description: 'The url where the artifact version is located e.g. docker.io/myapp/myimg:1.0.0.'
    required: true
  digest:
    description: 'The artifact digest that uniquely and immutably identifies the artifact.'
    required: false
  type:
    description: 'The type of the artifact. e.g. docker, maven'
    required: false

runs:
  using: "docker"
  image: "docker://public.ecr.aws/l7o7z1g8/actions/gha-register-build-artifact:main-9905592c24905185a67fc841703877862450549f"
  env:
    CLOUDBEES_API_URL: ${{ inputs.cloudbees-url }}
    CLOUDBEES_API_TOKEN: ${{ inputs.cloudbees-pat }}
    ARTIFACT_NAME: ${{ inputs.name }}
    ARTIFACT_VERSION: ${{ inputs.version }}
    ARTIFACT_URL: ${{ inputs.url }}
    ARTIFACT_DIGEST: ${{ inputs.digest }}
    ARTIFACT_TYPE: ${{ inputs.type }}
